from typing import Optional, Union

from db import db_connection
from db.db_connection import *
from db.model.cfb_model import CfbBaseModel
from pymongo import DeleteMany, DeleteOne, InsertOne, ReplaceOne, UpdateMany, UpdateOne

_WriteOp = Union[
    InsertOne,
    DeleteOne,
    DeleteMany,
    ReplaceOne,
    UpdateOne,
    UpdateMany,
]


def insert_many_operations(
    db_client: DbConnection,
    db: Databases,
    entities: tuple[CfbBaseModel],
    do_replace: bool,
    coll_op: bool = False,
) -> list[_WriteOp]:

    operations: list[_WriteOp] = []
    for entity in entities:
        op = insert_one_operation(
            db_client=db_client,
            db=db,
            entity=entity,
            do_replace=do_replace,
            coll_op=coll_op,
        )
        if op is not None:
            operations.append(op)

    return operations


def insert_one_operation(
    db_client: DbConnection,
    db: Databases,
    entity: CfbBaseModel | dict,
    do_replace: bool,
    model: Optional[ExtractionCollections | Type[CfbBaseModel]] = None,
    query: Optional[dict] = None,
    coll_op: bool = False,
) -> Optional[_WriteOp]:

    if db == Databases.extraction:
        if isinstance(entity, CfbBaseModel) or (
            model is not None and issubclass(model, CfbBaseModel)
        ):
            raise ValueError("Entity or model do not match extraction types")

    else:
        if model is not None and isinstance(ExtractionCollections):
            raise ValueError("Model must be instance of CfbBaseModel")

    if isinstance(entity, dict) and model is None:
        raise ValueError("Model type is required if the entity is a dictionary")

    if isinstance(entity, CfbBaseModel):
        if query is None:
            filter = entity.get_model_query()
        else:
            filter = query

        document = entity.model_dump()

    elif isinstance(entity, dict):
        if do_replace and query is None:
            raise ValueError("Query must be provided for dict entities")

        filter = query
        document = entity

    else:
        raise ValueError("Entity must be a CfbBaseModel or a dict")

    # Remove id fields if they exist since they will be auto-generated by MongoDB
    if db != Databases.extraction:
        document.pop("id", None)
        document.pop("_id", None)

    if coll_op:
        namespace = None
    else:
        if model is not None:
            namespace = db_client.get_collection_namespace(db, model)
        else:
            namespace = db_client.get_collection_namespace(db, type(entity))

    if do_replace:
        return ReplaceOne(
            namespace=namespace, filter=filter, replacement=document, upsert=True
        )
    else:
        return InsertOne(namespace=namespace, document=document)


def get_insert_operation_from_list(
    operations: list[_WriteOp], query: dict, namespace: str
) -> Optional[dict]:

    ops = [o for o in operations if o._namespace == namespace]
    for op in ops:
        doc = op._doc
        if all(doc[x] == query[x] for x in query):
            return doc


def get_random_entity(
    db_client: DbConnection,
    db: Databases = Databases.production,
    model: Optional[ExtractionCollections | type[CfbBaseModel]] = None,
) -> Optional[CfbBaseModel | dict]:
    """
    Returns a random entity from the database. The default database is production if not
    specified. If no model is specified, then a random one is used.
    """

    # Extraction model
    if db == Databases.extraction:
        if model is not None:
            if not isinstance(model, ExtractionCollections):
                raise Exception(
                    "Model must be of type ExtractionCollections for Extraction DB"
                )
            return db_client.get_cfb_collection(db, model).find_one()

        for coll in ExtractionCollections:
            entity = db_client.get_cfb_collection(db, coll).find_one()
            if entity is not None:
                return entity

    # CFB model
    else:
        if model is not None:
            if not issubclass(model, CfbBaseModel):
                raise Exception(
                    "Model must be a subclass of CfbBaseModel for Staging and Production DBs"
                )
            return db_client.get_cfb_repository(db, model).find_one_by({})

        for m in cfb_models:
            entity = db_client.get_cfb_repository(db, m).find_one_by({})
            if entity is not None:
                return entity

    return None
