openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /:
    get:
      summary: Root
      operationId: root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /data/team:
    get:
      tags:
      - data
      summary: Get Team
      operationId: get_team
      parameters:
      - name: school
        in: query
        required: false
        schema:
          type: string
          title: School
      - name: team_id
        in: query
        required: false
        schema:
          type: integer
          title: Team Id
      - name: year
        in: query
        required: false
        schema:
          type: integer
          default: 2025
          title: Year
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Team:
      properties:
        _id:
          anyOf:
          - type: string
          - type: 'null'
          title: Id
        team_id:
          type: integer
          title: Team Id
        year:
          type: integer
          title: Year
        school:
          type: string
          title: School
        conference_id:
          type: integer
          title: Conference Id
        classification:
          type: string
          title: Classification
        division:
          anyOf:
          - type: string
          - type: 'null'
          title: Division
        venue_id:
          anyOf:
          - type: integer
          - type: 'null'
          title: Venue Id
      type: object
      required:
      - team_id
      - year
      - school
      - conference_id
      - classification
      - division
      - venue_id
      title: Team
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
